### ISSUE TITLE
Packing XML from unpacked IMF Issue

### ISSUE THREAD

**Issue by JasonVanKerkhoven** [carleton-smart-grid/pythonUDPTools#2]
## Issue
Issue when:
1. Packing XML into IMF
2. Unpacking IMF back to XML
3. Packing XML back into IMF **(error occurs on this step)**

## Trace
```python
Traceback (most recent call last):
  File "packer.py", line 208, in <module>
    imf = pack(xml)
  File "packer.py", line 56, in pack
    root = et.fromstring(xmlContents)
  File "/home/jason/anaconda3/lib/python3.6/xml/etree/ElementTree.py", line 1314, in XML
    parser.feed(text)
xml.etree.ElementTree.ParseError: mismatched tag: line 1, column 222
```

**Comment by JasonVanKerkhoven** [comment]
literally one misplaced / character....
